### ISSUE TITLE
[CY-6630] Request to bump PMD to 6.51.0

### ISSUE THREAD

**Issue by tysonstewart** [codacy/codacy-pmd#108]
Codacy is currently using version 6.48.0. The PMD project had a bug through version 6.50.0 with JavaScript numerical literals that has been fixed in 6.51.0.

References:
[PMD 6.51.0 release notes](https://pmd.sourceforge.io/pmd-6.51.0/pmd_release_notes.html)
[Bug issue](https://github.com/pmd/pmd/issues/4165)

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out!

We bumped the version in [this PR](https://github.com/codacy/codacy-pmd/pull/109) and it's now live.

Feel free to open a new issue if you notice something irregular.

Best,
Stefan
