### ISSUE TITLE
[TS-697] Customise PMD rule

### ISSUE THREAD

**Issue by alivanni** [codacy/codacy-pmd#120]
Hello,

Could you please clarify how PMD customisation works under the hood. If I provide ruleset.xml will Codacy take own "default" ruleset and apply my file on top of it or will it just take my file? Other words, if I customise one existing rule in my ruleset - this rule is the only thing that going to be checked or default behaviour of all other rules will also be executed?
If Codacy will take only my ruleset.xml - how I can practically customise any rule? I mean I am quite happy with default set, but looks like single rule customisation will "disable" everything else.

Thanks,
Aleksandr

**Comment by DMarinhoCodacy** [comment]
Hello @alivanni 
If you use the ruleset.xml, Codacy will take into consideration only the rules you use in that file.
Not only for PMD but all tools with configuration files, if we scan a valid configuration file, we only use that file and not the default pattern's list.
Hope this clarifies your question.
Thanks,
David
